language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.2.2"
  # Faraday::ConnectionFailed: Could not generate DH keypair (Java::JavaLang::RuntimeException)
  # http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7044060
  #  - jruby-19mode # JRuby in 1.9 mode
  #  - rbx
  #  - "1.8.7"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
