dist: trusty
language: ruby
rvm:
  # - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.2.3"
  # - "jruby"
  #  - rbx
  #  - "1.8.7"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
